config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  get 'page/index'
  get 'page/about'
  get 'page/tutorial'
  get 'profile/index'
  get 'profile/faq'

  resources :activities

  namespace :profile do
    resources :projects do
      resources :telas do 
        resources :answers
        get 'relatorio' => 'telas#relatorio', :as => 'relatorio'
      end
      resources :invites
      get 'convidar' => 'projects#invite', :as => 'convidar'
      get 'resultado' => 'projects#resultado'
      get 'avaliar' => 'projects#avaliar', :as => 'avaliar'
    end 
    get 'para_avaliar' => 'projects#para_avaliar', :as => 'para_avaliar'
  end

  namespace :admin do
    resources :heuristics do
      resources :questions
    end
  end

  namespace :admin do
    resources :devices
  end

  devise_for :users, :controllers => { :registrations => :registrations }

  resources :ratings, only: :update

  root 'page#index'

end

app/models/admin/question.rb
class Admin::Question < ActiveRecord::Base
  belongs_to :heuristic
  has_many :answers, class_name: 'Profile::Answer'
  acts_as_list scope: :heuristic

  validates_presence_of :name

  has_attached_file :image, :styles => { :medium => "300x300>" }, 
  :storage => :dropbox,
  :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
  :default_url => "/images/:style/missing.png"
  
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :set_admin_question, only: [:show, :edit, :update, :destroy]
  before_action :get_heuristic
  before_action :authenticate_user!
  load_and_authorize_resource param_method: :admin_question_params

  # GET /admin/questions
  # GET /admin/questions.json
  def index
    @admin_questions = @heuristic.questions.paginate(page: params[:page], per_page: 10)
  end

  # GET /admin/questions/1
  # GET /admin/questions/1.json
  def show
    @id = params[:id]
    @admin_question = @heuristic.questions.find(@id)
  end

  # GET /admin/questions/new
  def new
    @admin_question = Admin::Question.new
  end

  # GET /admin/questions/1/edit
  def edit
  end

  # POST /admin/questions
  # POST /admin/questions.json
  def create
    @admin_question = @heuristic.questions.new(admin_question_params)

    respond_to do |format|
      if @admin_question.save
        format.html { redirect_to admin_heuristic_questions_path, notice: 'Pergunta criada com sucesso.' }
        format.json { render :show, status: :created, location: admin_heuristic_questions_path }
      else
        format.html { render :new }
        format.json { render json: @admin_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/questions/1
  # PATCH/PUT /admin/questions/1.json
  def update
    respond_to do |format|
      if @admin_question.update(admin_question_params)
        format.html { redirect_to admin_heuristic_questions_path, notice: 'Pergunta atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: admin_heuristic_questions_path }
      else
        format.html { render :edit }
        format.json { render json: @admin_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/questions/1
  # DELETE /admin/questions/1.json
  def destroy
    @admin_question.destroy
    respond_to do |format|
      format.html { redirect_to admin_heuristic_questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_question
      @admin_question = Admin::Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_question_params
      params.require(:admin_question).permit(:name, :description, :heuristic_id, :exemplo, :image)
    end

    def get_heuristic
      @heuristic = Admin::Heuristic.find(params[:heuristic_id])
    end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/views/admin/questions/_form.html.erb
<%= form_for [@heuristic, @admin_question],:url => admin_heuristic_questions_path, :html => { :multipart => true }  do |f| %>
  <% if @admin_question.errors.any? %>
    <div class="alert alert-danger">
      <h4><i class="glyphicon glyphicon-remove-sign"></i> Erro ao salvar pergunta:</h4>

      <ul class="list-unstyled">
      <% @admin_question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Pergunta" %> <i class="tip glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Titulo da pergunta."></i><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Descrição" %> <i class="tip glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Uma breve descrição/explicação da pergunta (se necessário)."></i><br>
    <%= f.text_area :description, :rows => '12', :class => 'form-control' %>
  </div>

  <h4>Adicione um exemplo para ajudar no entendimento da pergunta:</h4>

  <div class="form-group">
    <%= f.label :image, "Imagem de exemplo" %> <i class="tip glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Imagem de exemplo."></i><br>
    <%= f.file_field :image, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :exemplo, "Exemplo" %> <i class="tip glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Texto explicando o exemplo."></i><br>
    <%= f.text_area :exemplo, :rows => '12', :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/questions/edit.html.erb
<% titulo "Editar pergunta" %>

<%= render "layouts/admin_menu" %>

<div class="container-default">

<div class="page-header text-center">
	<h1>Editar pergunta</h1>
</div>

<%= form_for [@heuristic, @admin_question],:url => admin_heuristic_question_path, :html => { :multipart => true } do |f| %>
  <% if @admin_question.errors.any? %>
    <div class="alert alert-danger">
      <h4><i class="glyphicon glyphicon-remove-sign"></i> Erro ao salvar pergunta:</h4>

      <ul class="list-unstyled">
      <% @admin_question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Pergunta" %> <i class="tip glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Titulo da pergunta."></i><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Descrição" %> <i class="tip glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Uma breve descrição/explicação da pergunta (se necessário)."></i><br>
    <%= f.text_area :description, :rows => '12', :class => 'form-control' %>
  </div>
  <h4>Adicione um exemplo para ajudar no entendimento da pergunta:</h4>

  <div class="form-group">
    <%= f.label :image, "Imagem de exemplo" %> <i class="tip glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Imagem de exemplo."></i><br>
    <%= f.file_field :image, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :exemplo, "Exemplo" %> <i class="tip glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Texto explicando o exemplo."></i><br>
    <%= f.text_area :exemplo, :rows => '12', :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>
<div class="well well-sm">
<%= link_to '<i class="glyphicon glyphicon-chevron-left"></i> Voltar'.html_safe, admin_heuristic_questions_path, :class => 'btn btn-default' %>
</div>

</div>

app/views/admin/questions/index.html.erb
<% titulo "Perguntas para heurística #{@heuristic.name}" %>

<%= render "layouts/admin_menu" %>

<div class="container-default">
<div class="page-header">
  <h1>Heurísticas de: <%= @heuristic.name %></h1>
</div>

<div class="well well-sm">
  <%= link_to '<i class="glyphicon glyphicon-asterisk"></i> Nova heurística'.html_safe, new_admin_heuristic_question_path, :class => 'btn btn-primary' %>
  <%= link_to '<i class="glyphicon glyphicon-chevron-left"></i> Voltar'.html_safe, admin_heuristics_path, :class => 'btn btn-default' %>
</div>

<div class="table-responsive text-center">
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th class="text-center col-md-1">#</th>
      <th class="text-center">Heurística</th>
      <th class="text-center">Descrição</th>
      <th class="col-md-1"></th>
      <th class="col-md-1"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_questions.each do |admin_question| %>
      <tr>
        <td><%= admin_question.position %></td>
        <td><%= link_to admin_question.name, admin_heuristic_question_path(@heuristic, admin_question) %></td>
        <td><%= admin_question.description %></td>
        <td><%= link_to '<i class="tip glyphicon glyphicon-pencil" data-toggle="tooltip" data-placement="top" title="Editar"></i>'.html_safe, edit_admin_heuristic_question_path(@heuristic, admin_question) %></td>
        <td><%= link_to '<i class="tip glyphicon glyphicon-trash" data-toggle="tooltip" data-placement="top" title="Deletar"></i>'.html_safe, admin_heuristic_question_path(@heuristic, admin_question), method: :delete, data: { confirm: 'Tem certeza que deseja deletar essa pergunta?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="text-center">

</div>

</div>

app/views/admin/questions/new.html.erb
<% titulo "Nova pergunta" %>

<%= render "layouts/admin_menu" %>

<div class="container-default">

<div class="page-header text-center">	
	<h1>Nova pergunta</h1>
</div>

<%= render 'form' %>

<div class="well well-sm">
<%= link_to '<i class="glyphicon glyphicon-chevron-left"></i> Voltar'.html_safe, admin_heuristic_questions_path, :class => 'btn btn-default' %>
</div>

</div>

app/views/admin/questions/show.html.erb
<% titulo "Pergunta #{@admin_question.name}" %>

<%= render "layouts/admin_menu" %>

<div class="container-default">

<div class="page-header text-center">
	<h1><%= @admin_question.name %><br><small><%= @admin_question.heuristic.name %></small></h1>
</div>

<p class="text-center">
  <%= @admin_question.description %>
</p>

<% if @admin_question.exemplo.nil? %>
	<div class="text-center well well-incolor">
		<h2>Não há exemplo para essa pergunta</h2>
	</div>
<% else %>	
	<div class="row well">
		<div class="page-header text-center">
			<h2>Exemplo</h2>
		</div>
		<div class="col-md-4">
			<%= image_tag @admin_question.image.url(:medium) %>
		</div>
		<div class="col-md-6">
			<p><%= @admin_question.exemplo %></p>		
		</div>
	</div>
<% end %>


<div class="well well-sm">
<%= link_to '<i class="glyphicon glyphicon-edit"></i> Editar'.html_safe, edit_admin_heuristic_question_path(@heuristic, @admin_question), :class => 'btn btn-primary' %>
<%= link_to '<i class="glyphicon glyphicon-chevron-left"></i> Voltar'.html_safe, admin_heuristic_questions_path, :class => 'btn btn-default' %>
</div>

</div>