config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  get 'page/index'
  get 'page/about'
  get 'page/tutorial'
  get 'profile/index'
  get 'profile/faq'

  resources :activities

  namespace :profile do
    resources :projects do
      resources :telas do 
        resources :answers
        get 'relatorio' => 'telas#relatorio', :as => 'relatorio'
      end
      resources :invites
      get 'convidar' => 'projects#invite', :as => 'convidar'
      get 'resultado' => 'projects#resultado'
      get 'avaliar' => 'projects#avaliar', :as => 'avaliar'
    end 
    get 'para_avaliar' => 'projects#para_avaliar', :as => 'para_avaliar'
  end

  namespace :admin do
    resources :heuristics do
      resources :questions
    end
  end

  namespace :admin do
    resources :devices
  end

  devise_for :users, :controllers => { :registrations => :registrations }

  resources :ratings, only: :update

  root 'page#index'

end

app/models/admin/device.rb
class Admin::Device < ActiveRecord::Base
  	has_many :heuristic
	has_many :project

	has_attached_file :icon, 
	:storage => :dropbox,
	:dropbox_credentials => Rails.root.join("config/dropbox.yml"),	
	:styles => { :thumb => "24x24>" }
	
  	validates_attachment_content_type :icon, :content_type => /\Aimage\/.*\Z/

	validates_presence_of :name
end

app/controllers/admin/devices_controller.rb
class Admin::DevicesController < ApplicationController
  before_action :set_admin_device, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource param_method: :admin_device_params

  # GET /admin/devices
  # GET /admin/devices.json
  def index
    @admin_devices = Admin::Device.paginate(page: params[:page], per_page: 10)
  end

  # GET /admin/devices/1
  # GET /admin/devices/1.json
  def show
  end

  # GET /admin/devices/new
  def new
    @admin_device = Admin::Device.new
  end

  # GET /admin/devices/1/edit
  def edit
  end

  # POST /admin/devices
  # POST /admin/devices.json
  def create
    @admin_device = Admin::Device.new(admin_device_params)

    respond_to do |format|
      if @admin_device.save
        format.html { redirect_to admin_devices_url, notice: 'Dispositivo criado com sucesso.' }
        format.json { render :show, status: :created, location: @admin_device }
      else
        format.html { render :new }
        format.json { render json: @admin_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/devices/1
  # PATCH/PUT /admin/devices/1.json
  def update
    respond_to do |format|
      if @admin_device.update(admin_device_params)
        format.html { redirect_to admin_devices_url, notice: 'Dispositivo atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @admin_device }
      else
        format.html { render :edit }
        format.json { render json: @admin_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/devices/1
  # DELETE /admin/devices/1.json
  def destroy
    @admin_device.destroy
    respond_to do |format|
      format.html { redirect_to admin_devices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_device
      @admin_device = Admin::Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_device_params
      params.require(:admin_device).permit(:name, :icon)
    end
end

app/helpers/admin/devices_helper.rb
module Admin::DevicesHelper
end

app/views/admin/devices/_form.html.erb
<%= form_for(@admin_device) do |f| %>
  <% if @admin_device.errors.any? %>
    <div class="alert alert-danger">
      <h4><i class="glyphicon glyphicon-remove-sign"></i> Erro ao salvar dispositivo:</h4>

      <ul class="list-unstyled">
      <% @admin_device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Nome" %> <i class="tip glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Dispositivos que aceitam interfaces para avaliação. Ex: TV, Mobile, Desktop."></i><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :icon, "Ícone" %> <i class="tip glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Ícone para representar o dispositivo."></i><br>
    <%= f.file_field :icon, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/devices/edit.html.erb
<% titulo "Editar dispositivo" %>

<%= render "layouts/admin_menu" %>

<div class="container-default">

<div class="page-header text-center">
	<h1>Editar dispositivo</h1>
</div>

<%= render 'form' %>

<div class="well well-sm">
<%= link_to '<i class="glyphicon glyphicon-chevron-left"></i> Voltar'.html_safe, admin_devices_path, :class => 'btn btn-default' %>
</div>

</div>

app/views/admin/devices/index.html.erb
<% titulo "Listagem de dispositivos" %>

<%= render "layouts/admin_menu" %>

<div class="container-default">
<div class="page-header">
  <h1>Listagem de dispositivos</h1>
</div>

<div class="well well-sm">
  <%= link_to '<i class="glyphicon glyphicon-asterisk"></i> Novo Dispositivo'.html_safe, new_admin_device_path, :class => 'btn btn-primary' %>
</div>

<div class="table-responsive text-center">
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th class="text-center col-md-2">Ícone</th>
      <th class="text-center">Dispositivo</th>
      <th class="col-md-1"></th>
      <th class="col-md-1"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_devices.each do |admin_device| %>
      <tr>
      <td><%= image_tag admin_device.icon.url(:thumb) %></td>
        <td><%= link_to admin_device.name, admin_device %></td>
        <td><%= link_to '<i class="tip glyphicon glyphicon-pencil" data-toggle="tooltip" data-placement="top" title="Editar"></i>'.html_safe, edit_admin_device_path(admin_device) %></td>
        <td><%= link_to '<i class="tip glyphicon glyphicon-trash" data-toggle="tooltip" data-placement="top" title="Deletar"></i>'.html_safe, admin_device, method: :delete, data: { confirm: 'Tem certeza que deseja deletar esse dispositivo?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="text-center">
<%= will_paginate @admin_devices %>
</div>

</div>

app/views/admin/devices/new.html.erb
<% titulo "Novo dispositivo" %>

<%= render "layouts/admin_menu" %>

<div class="container-default">

<div class="page-header text-center">
	<h1>Novo dispositivo</h1>
</div>

<%= render 'form' %>

<div class="well well-sm">
<%= link_to '<i class="glyphicon glyphicon-chevron-left"></i> Voltar'.html_safe, admin_devices_path, :class => 'btn btn-default' %>
</div>

</div>

app/views/admin/devices/show.html.erb
<% titulo "Dispositivo: #{@admin_device.name}" %>

<%= render "layouts/admin_menu" %>

<div class="container-default">

<div class="page-header text-center">
  <h1><%= @admin_device.name %></h1>
</div>

<p class="text-center">
  <%= image_tag @admin_device.icon.url %>
</p>

<div class="well well-sm">
	<%= link_to '<i class="glyphicon glyphicon-edit"></i> Editar'.html_safe, edit_admin_device_path(@admin_device), :class => 'btn btn-primary' %>
	<%= link_to '<i class="glyphicon glyphicon-chevron-left"></i> Voltar'.html_safe, admin_devices_path, :class => 'btn btn-default' %>
</div>

</div>