config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  get 'page/index'
  get 'page/about'
  get 'page/tutorial'
  get 'profile/index'
  get 'profile/faq'

  resources :activities

  namespace :profile do
    resources :projects do
      resources :telas do 
        resources :answers
        get 'relatorio' => 'telas#relatorio', :as => 'relatorio'
      end
      resources :invites
      get 'convidar' => 'projects#invite', :as => 'convidar'
      get 'resultado' => 'projects#resultado'
      get 'avaliar' => 'projects#avaliar', :as => 'avaliar'
    end 
    get 'para_avaliar' => 'projects#para_avaliar', :as => 'para_avaliar'
  end

  namespace :admin do
    resources :heuristics do
      resources :questions
    end
  end

  namespace :admin do
    resources :devices
  end

  devise_for :users, :controllers => { :registrations => :registrations }

  resources :ratings, only: :update

  root 'page#index'

end

app/models/admin/heuristic.rb
class Admin::Heuristic < ActiveRecord::Base
  	belongs_to :device
	has_many :questions, -> { order("position ASC") }
	has_many :projects, class_name: 'Profile::Project'
	
	validates_presence_of :name

end

app/controllers/admin/heuristics_controller.rb
class Admin::HeuristicsController < ApplicationController
  before_action :set_admin_heuristic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource param_method: :admin_heuristic_params

  # GET /admin/heuristics
  # GET /admin/heuristics.json
  def index
    @admin_heuristics = Admin::Heuristic.paginate(page: params[:page], per_page: 10)
  end

  # GET /admin/heuristics/1
  # GET /admin/heuristics/1.json
  def show
  end

  # GET /admin/heuristics/new
  def new
    @admin_heuristic = Admin::Heuristic.new
  end

  # GET /admin/heuristics/1/edit
  def edit
  end

  # POST /admin/heuristics
  # POST /admin/heuristics.json
  def create
    @admin_heuristic = Admin::Heuristic.new(admin_heuristic_params)

    respond_to do |format|
      if @admin_heuristic.save
        format.html { redirect_to admin_heuristics_url, notice: 'Heuristica criada com sucesso.' }
        format.json { render :index, status: :created, location: @admin_heuristic }
      else
        format.html { render :new }
        format.json { render json: @admin_heuristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/heuristics/1
  # PATCH/PUT /admin/heuristics/1.json
  def update
    respond_to do |format|
      if @admin_heuristic.update(admin_heuristic_params)
        format.html { redirect_to admin_heuristics_url, notice: 'Heuristica atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @admin_heuristic }
      else
        format.html { render :edit }
        format.json { render json: @admin_heuristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/heuristics/1
  # DELETE /admin/heuristics/1.json
  def destroy
    @admin_heuristic.destroy
    respond_to do |format|
      format.html { redirect_to admin_heuristics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_heuristic
      @admin_heuristic = Admin::Heuristic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_heuristic_params
      params.require(:admin_heuristic).permit(:name, :description, :device_id)
    end
end

app/helpers/admin/heuristics_helper.rb
module Admin::HeuristicsHelper
end

app/views/admin/heuristics/_form.html.erb
<%= form_for(@admin_heuristic) do |f| %>
  <% if @admin_heuristic.errors.any? %>
    <div class="alert alert-danger">
      <h4><i class="glyphicon glyphicon-remove-sign"></i> Erro ao salvar heurística:</h4>

      <ul class="list-unstyled">
      <% @admin_heuristic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Nome" %> <i class="tip glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Nome da heurística."></i><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Descrição" %> <i class="tip glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Uma breve descrição sobre essa heurística."></i><br>
    <%= f.text_area :description, :rows => '12', :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :device_id, "Dispositivo" %> <i class="tip glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="top" title="Para qual dispositivo essa heurística se aplica."></i><br>
    <%= f.collection_select(:device_id, Admin::Device.order(:name),:id,:name, { include_blank: false }, { class: 'form-control'}) %>
  </div>
  <div class="form-group">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/heuristics/edit.html.erb
<% titulo "Editar heurística" %>

<%= render "layouts/admin_menu" %>

<div class="container-default">

<div class="page-header text-center">
	<h1>Editar heurística</h1>
</div>

<%= render 'form' %>

<div class="well well-sm">
<%= link_to '<i class="glyphicon glyphicon-chevron-left"></i> Voltar'.html_safe, admin_heuristics_path, :class => 'btn btn-default' %>
</div>

</div>

app/views/admin/heuristics/index.html.erb
<% titulo "Listagem de heurísticas" %>

<%= render "layouts/admin_menu" %>

<div class="container-default">
<div class="page-header">
  <h1>Tipos de heurísticas</h1>
</div>

<div class="well well-sm">
  <%= link_to '<i class="glyphicon glyphicon-asterisk"></i> Nova Heurística'.html_safe, new_admin_heuristic_path, :class => 'btn btn-primary' %>
</div>

<div class="table-responsive text-center">
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th class="text-center">Nome</th>
      <th class="text-center">Descrição</th>
      <th class="text-center col-md-2">Dispositivo</th>
      <th class="col-md-1"></th>
      <th class="col-md-1"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_heuristics.each do |admin_heuristic| %>
      <tr>
        <td><%= link_to admin_heuristic.name, [admin_heuristic, :questions] %></td>
        <td><%= admin_heuristic.description %></td>
        <td><%= image_tag admin_heuristic.device.icon.url(:thumb) %>  <%= admin_heuristic.device.name %></td>
        <td><%= link_to '<i class="tip glyphicon glyphicon-pencil" data-toggle="tooltip" data-placement="top" title="Editar"></i>'.html_safe, edit_admin_heuristic_path(admin_heuristic) %></td>
        <td><%= link_to '<i class="tip glyphicon glyphicon-trash" data-toggle="tooltip" data-placement="top" title="Deletar"></i>'.html_safe, admin_heuristic, method: :delete, data: { confirm: 'Tem certeza que deseja deletar essa heurística e suas perguntas?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="text-center">
<%= will_paginate @admin_heuristics %>
</div>

</div>

app/views/admin/heuristics/new.html.erb
<% titulo "Nova heurística" %>

<%= render "layouts/admin_menu" %>

<div class="container-default">

<div class="page-header text-center">
	<h1>Nova heurística</h1>
</div>

<%= render 'form' %>

<div class="well well-sm">
<%= link_to '<i class="glyphicon glyphicon-chevron-left"></i> Voltar'.html_safe, admin_heuristics_path, :class => 'btn btn-default' %>
</div>

</div>

app/views/admin/heuristics/show.html.erb
<% titulo "Heurística: #{@admin_heuristic.name}" %>

<%= render "layouts/admin_menu" %>

<div class="container-default">

<div class="page-header text-center">
	<h1><%= @admin_heuristic.name %> <br><small><%= @admin_heuristic.device.name %></small></h1>
</div>

<p class="text-center">
  <%= @admin_heuristic.description %>
</p>

<div class="table-responsive text-center">
<table class="table table-striped table-bordered">
  <thead>
    <tr>
    <th class="text-center col-md-1">#</th>
      <th class="text-center">Pergunta</th>
      <th class="text-center">Descrição</th>
      <th class="col-md-1"></th>
      <th class="col-md-1"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_questions.each do |admin_question| %>
      <tr>
        <td><%= admin_question.id %></td>
        <td><%= link_to admin_question.name, admin_question %></td>
        <td><%= admin_question.description %></td>
        <td><%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_admin_question_path(admin_question) %></td>
        <td><%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, admin_question, method: :delete, data: { confirm: 'Tem certeza que deseja deletar essa pergunta?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<div class="well well-sm">
<%= link_to '<i class="glyphicon glyphicon-edit"></i> Editar'.html_safe, edit_admin_heuristic_path(@admin_heuristic), :class => 'btn btn-primary' %> 
<%= link_to '<i class="glyphicon glyphicon-chevron-left"></i> Voltar'.html_safe, admin_heuristics_path, :class => 'btn btn-default' %>
</div>

</div>