config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  get 'page/index'
  get 'page/about'
  get 'page/tutorial'
  get 'profile/index'
  get 'profile/faq'

  resources :activities

  namespace :profile do
    resources :projects do
      resources :telas do 
        resources :answers
        get 'relatorio' => 'telas#relatorio', :as => 'relatorio'
      end
      resources :invites
      get 'convidar' => 'projects#invite', :as => 'convidar'
      get 'resultado' => 'projects#resultado'
      get 'avaliar' => 'projects#avaliar', :as => 'avaliar'
    end 
    get 'para_avaliar' => 'projects#para_avaliar', :as => 'para_avaliar'
  end

  namespace :admin do
    resources :heuristics do
      resources :questions
    end
  end

  namespace :admin do
    resources :devices
  end

  devise_for :users, :controllers => { :registrations => :registrations }

  resources :ratings, only: :update

  root 'page#index'

end

app/views/layouts/_admin_menu.html.erb
<div class="container-default">
  <div class="btn-group btn-group-justified">
  	<a class="btn btn-lg btn-default" disabled="disabled"><span class="glyphicon glyphicon-th"></span> Menu</a>
  	<%= active_link_to "Heurísticas", admin_heuristics_path, :class => 'btn btn-lg btn-default' %>
    <%= active_link_to "Dispositivos", admin_devices_path, :class => 'btn btn-lg btn-default' %>
    <%= active_link_to "Minha conta", edit_user_registration_path, :class => 'btn btn-lg btn-default' %>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>UI Report <%= yield :titulo %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Ver navegação</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "UI Report", admin_index_path, :class => "navbar-brand" %>
    </div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class='glyphicon glyphicon-user'></i> Bem-vindo, <%= current_user.name %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "<i class='glyphicon glyphicon-cog'></i> Painel Adm".html_safe, admin_index_path %></li>
              <li><%= link_to "<i class='glyphicon glyphicon glyphicon-edit'></i> Editar minha conta".html_safe, edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "<i class='glyphicon glyphicon-off'></i> Logout".html_safe, destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice %>
  <p class="alert alert-success alert-margin"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><span class="glyphicon glyphicon-ok-sign"></span> <%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-warning alert-margin"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><span class="glyphicon glyphicon-exclamation-sign"></span> <%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>UI Report <%= yield :titulo %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Ver navegação</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "UI Report", "/", :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<!--       <ul class="nav navbar-nav">
        <li><%= link_to "Tutorial", page_tutorial_path %></li>
      </ul> -->
      <ul class="nav navbar-nav navbar-right">
        <li><form><%= link_to "<i class='glyphicon glyphicon-log-in'></i> Entrar".html_safe, new_user_session_path,:class => "btn btn-primary navbar-btn", :style => "margin-right:5px" %></form></li>
        <li><form><%= link_to "<i class='glyphicon glyphicon-asterisk'></i> Criar conta".html_safe, new_user_registration_path,:class => "btn btn-default navbar-btn" %></form></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice %>
  <p class="alert alert-success alert-margin"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><span class="glyphicon glyphicon-ok-sign"></span> <%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-warning alert-margin"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><span class="glyphicon glyphicon-exclamation-sign"></span> <%= alert %></p>
<% end %>

<div class="content-margin">  
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>UI Report <%= yield :titulo %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top hidden-print" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Ver navegação</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "UI Report", profile_index_path, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> 
      <ul class="nav navbar-nav text-center">
        <li><%= link_to "Meus Projetos", profile_projects_path %></li>
        <li><%= link_to "Projetos para avaliação", profile_para_avaliar_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right text-center">
        <li><form><%= link_to "<i class='glyphicon glyphicon-asterisk'></i> Novo projeto".html_safe, new_profile_project_path, :class => 'btn btn-primary navbar-btn' %></form></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <% if current_user.avatar.exists? %>
          <%= image_tag current_user.avatar.url(:thumb), :class => "avatar-menu navbar-text img-circle" %>
      <% else %>
        <%= image_tag("avatar_medium.png", :class => 'avatar-menu navbar-text img-circle') %>
      <% end %>

       <%= current_user.name %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "<i class='glyphicon glyphicon-cog'></i> Configurar perfil".html_safe, edit_user_registration_path %></li>
            <li><%= link_to "<i class='glyphicon glyphicon-question-sign'></i> F.A.Q.".html_safe, profile_faq_path %></li>
            <li class="divider"></li>
            <li><%= link_to "<i class='glyphicon glyphicon-off'></i> Logout".html_safe, destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<% if notice %>
  <p class="alert alert-success alert-margin hidden-print"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><span class="glyphicon glyphicon-ok-sign"></span> <%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-warning alert-margin hidden-print"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><span class="glyphicon glyphicon-exclamation-sign"></span> <%= alert %></p>
<% end %>
<div class="content-margin">  
  <%= yield %>
</div>

</body>
</html>